credentials:
  usernames:
    cherkani:
      email: cherkani@gmail.com
      name: Cherkani
      password: abc # To be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: def # To be replaced with hashed password
    bennaneilyass:
      email: bennane123@gmail.com
      name: Bennane
      password: def # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com